// Generated by gencpp from file biox_read/FSR.msg
// DO NOT EDIT!


#ifndef BIOX_READ_MESSAGE_FSR_H
#define BIOX_READ_MESSAGE_FSR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace biox_read
{
template <class ContainerAllocator>
struct FSR_
{
  typedef FSR_<ContainerAllocator> Type;

  FSR_()
    : data()  {
    }
  FSR_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::biox_read::FSR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::biox_read::FSR_<ContainerAllocator> const> ConstPtr;

}; // struct FSR_

typedef ::biox_read::FSR_<std::allocator<void> > FSR;

typedef boost::shared_ptr< ::biox_read::FSR > FSRPtr;
typedef boost::shared_ptr< ::biox_read::FSR const> FSRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::biox_read::FSR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::biox_read::FSR_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::biox_read::FSR_<ContainerAllocator1> & lhs, const ::biox_read::FSR_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::biox_read::FSR_<ContainerAllocator1> & lhs, const ::biox_read::FSR_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace biox_read

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::biox_read::FSR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::biox_read::FSR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::biox_read::FSR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::biox_read::FSR_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::biox_read::FSR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::biox_read::FSR_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::biox_read::FSR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::biox_read::FSR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::biox_read::FSR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "biox_read/FSR";
  }

  static const char* value(const ::biox_read::FSR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::biox_read::FSR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
;
  }

  static const char* value(const ::biox_read::FSR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::biox_read::FSR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FSR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::biox_read::FSR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::biox_read::FSR_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOX_READ_MESSAGE_FSR_H
