# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from biox_read/IMU.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class IMU(genpy.Message):
  _md5sum = "7d7d0d3dc06e3fee1ce2f3a62d5b110c"
  _type = "biox_read/IMU"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point gravity
geometry_msgs/Point gyro
geometry_msgs/Point linear_acceleration
geometry_msgs/Point euler
geometry_msgs/Quaternion Quaternion
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['gravity','gyro','linear_acceleration','euler','Quaternion']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Quaternion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gravity,gyro,linear_acceleration,euler,Quaternion

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMU, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.gravity is None:
        self.gravity = geometry_msgs.msg.Point()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Point()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Point()
      if self.euler is None:
        self.euler = geometry_msgs.msg.Point()
      if self.Quaternion is None:
        self.Quaternion = geometry_msgs.msg.Quaternion()
    else:
      self.gravity = geometry_msgs.msg.Point()
      self.gyro = geometry_msgs.msg.Point()
      self.linear_acceleration = geometry_msgs.msg.Point()
      self.euler = geometry_msgs.msg.Point()
      self.Quaternion = geometry_msgs.msg.Quaternion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_16d().pack(_x.gravity.x, _x.gravity.y, _x.gravity.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.euler.x, _x.euler.y, _x.euler.z, _x.Quaternion.x, _x.Quaternion.y, _x.Quaternion.z, _x.Quaternion.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gravity is None:
        self.gravity = geometry_msgs.msg.Point()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Point()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Point()
      if self.euler is None:
        self.euler = geometry_msgs.msg.Point()
      if self.Quaternion is None:
        self.Quaternion = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 128
      (_x.gravity.x, _x.gravity.y, _x.gravity.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.euler.x, _x.euler.y, _x.euler.z, _x.Quaternion.x, _x.Quaternion.y, _x.Quaternion.z, _x.Quaternion.w,) = _get_struct_16d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_16d().pack(_x.gravity.x, _x.gravity.y, _x.gravity.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.euler.x, _x.euler.y, _x.euler.z, _x.Quaternion.x, _x.Quaternion.y, _x.Quaternion.z, _x.Quaternion.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gravity is None:
        self.gravity = geometry_msgs.msg.Point()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Point()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Point()
      if self.euler is None:
        self.euler = geometry_msgs.msg.Point()
      if self.Quaternion is None:
        self.Quaternion = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 128
      (_x.gravity.x, _x.gravity.y, _x.gravity.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.euler.x, _x.euler.y, _x.euler.z, _x.Quaternion.x, _x.Quaternion.y, _x.Quaternion.z, _x.Quaternion.w,) = _get_struct_16d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16d = None
def _get_struct_16d():
    global _struct_16d
    if _struct_16d is None:
        _struct_16d = struct.Struct("<16d")
    return _struct_16d
